In [7]:
import numpy as np
arr=np.array([1,3,4,5,6,6])
print(arr)
print(type(arr))
arr.shape #It tells about the dimension of array


[1 3 4 5 6 6]
<class 'numpy.ndarray'>


(6,)

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=arr1.reshape(1,6)
arr1.shape
arr2.shape

(1, 6)

In [ ]:
# arrange() same like range function in Python but arange() will return numpy array 
numbers=np.arange(0,10,2).reshape(5,1)
print(numbers)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [19]:
# Now take about 2D Array
array=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
array.shape
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
# ones(),eye( Func for identity Matrix)
ones_matrix=np.ones((4,4))
print(f"This is an Ones Matrix:\n{ones_matrix}")
identity_matrix=np.eye(4)
print(f"This is an Identity Matrix:\n{identity_matrix}")

This is an Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
This is an Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(f"Array:\n{arr3}")
print("Shape:\n",arr3.shape)
print("Numbers of Dimensions:",arr3.ndim)
print("Size(Number of Elements):",arr3.size)
print("Data_Type:",arr3.dtype)
print("Item size (in Bytes):",arr3.itemsize)

Array:
[[1 2 3 4]
 [5 6 7 8]]
Shape:
 (2, 4)
Numbers of Dimensions: 2
Size(Number of Elements): 8
Data_Type: int64
Item size (in Bytes): 8


In [48]:
# Numpy Vectorized Operations
s1=np.array([1,2,3,4,5])
s2=np.array([6,7,8,9,10])
print("Addition:",s1+s2) #it will perform addition element wise 
print("Substraction:",s1-s2)
print("Multiplication:",s1*s2)
print("Division:",s1/s2)


Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [53]:
s3=np.array([1,2,3,4,5])
#Sqaure Root of Array
print("Sqaure Root of Array is:",np.sqrt(s3))
#Exponential "Euler Number e power Calculation"
print("Exponential:",np.exp(s3))
#Sin 
print("Sin Values are:",np.sin(s3))
# Natural Log
print("Log of Array are:",np.log(s3))

Sqaure Root of Array is: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin Values are: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log of Array are: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## Fetching element using indexing and slicing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0]) #first one indicate row and Second one indicate column
print(arr[1:,2:])


1
[[ 7  8]
 [11 12]]


In [61]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [62]:
# Modify array elements
arr[0][0]=3

In [63]:
arr

array([[ 3,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
arr[1:]=100

In [65]:
arr

array([[  3,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]
