In [7]:
import numpy as np
arr=np.array([1,3,4,5,6,6])
print(arr)
print(type(arr))
arr.shape #It tells about the dimension of array


[1 3 4 5 6 6]
<class 'numpy.ndarray'>


(6,)

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=arr1.reshape(1,6)
arr1.shape
arr2.shape

(1, 6)

In [ ]:
# arrange() same like range function in Python but arange() will return numpy array 
numbers=np.arange(0,10,2).reshape(5,1)
print(numbers)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [19]:
# Now take about 2D Array
array=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
array.shape
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
# ones(),eye( Func for identity Matrix)
ones_matrix=np.ones((4,4))
print(f"This is an Ones Matrix:\n{ones_matrix}")
identity_matrix=np.eye(4)
print(f"This is an Identity Matrix:\n{identity_matrix}")

This is an Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
This is an Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(f"Array:\n{arr3}")
print("Shape:\n",arr3.shape)
print("Numbers of Dimensions:",arr3.ndim)
print("Size(Number of Elements):",arr3.size)
print("Data_Type:",arr3.dtype)
print("Item size (in Bytes):",arr3.itemsize)

Array:
[[1 2 3 4]
 [5 6 7 8]]
Shape:
 (2, 4)
Numbers of Dimensions: 2
Size(Number of Elements): 8
Data_Type: int64
Item size (in Bytes): 8
